### PR TITLE
Upgrade to pgstudio 2.0

### PR DESCRIPTION
**Pull request by erezny**
using tomcat 8, jre 1.8

### CODE REVIEW

**Comment by lukasmartinelli** [comment]
Very nice. Thanks for the PR.

**Comment by dannejosefsson** [comment]
@lukasmartinelli: It would be sweet if you pushed this to Docker hub as well. That version is still at 1.2.

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli: It would be sweet if you pushed this to Docker hub as well. That version is still at 1.2.

It is actually set to autobuild. I triggered a new build manually now.

**Comment by dannejosefsson** [comment]
Ah, weird that it didn't fetch it. I can confirm that it is on docker hub now. Thanks!

**Pull request merged**
